### PR TITLE
Runtime device

### PR DESCRIPTION
**Pull request by MaxHerbs**
Added runtimedevice and schema description

### CODE REVIEW

**Comment by marcelldls** [comment]
Can I suggest we rather pass through only `runtimeClassName` into the spec dictionary?
The reasons being:
- Potential for clashes with existing keys
- Not inventing new properties in the chart (please point to existing schemas so we get the correct validation + dont have to maintain them)

My suggestion is
```
    spec:
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- end }}
```

**Comment by gilesknap** [comment]
@marcelldls I asked Richard to use the approach you used for hostMounts etc.

I agree that this opens up clashes as you can override the whole podSpec, but I also did not want to release a new ec-helm-charts each time we needed a new podSpec item. 

In my head the model is that we provide opinionated templating for the fields that most IOCs will make use of, but leave customisation capabilities reasonably open.

I'm not strongly attached to this model and @marcelldls helm skills are much more fresh that mine so I'll go with what you vote for.

@MaxHerbs to do the schema as Marcell requests, you want to refer out to the K8S manifest schema that you are duplicating e.g. see "resources": just above your addition to the template.

**Comment by MaxHerbs** [comment]
I've made the changed but haven't tested it. The beamline is in use today so follow up when I've verified it.

**Comment by gilesknap** [comment]
OK, lets go with that then. @MaxHerbs please can you switch to @marcelldls' suggestion above and update the schema to reflect that change.

(I'm not sure that calling out to the K8S schema would work for a single field - but if it does I guess you will get the correct K8S description of the field and formatting restrictions for the string)

**Comment by marcelldls** [comment]
@MaxHerbs The schema would look as follows:
```
        "runtimeClassName": {
          "$ref": "https://kubernetesjsonschema.dev/v1.18.1/_definitions.json#/definitions/io.k8s.api.core.v1.PodSpec/properties/runtimeClassName"
        },
```

**Comment by marcelldls** [comment]
Thanks! LGTM

**Comment by gilesknap** [comment]
Thanks both, merging ...

**Comment by gilesknap** [comment]
@MaxHerbs you can do the honours and release this as 4.1.3.

Do it from this page https://github.com/epics-containers/ec-helm-charts/releases
- Draft new Release
- Choose Tag and type in 4.1.3
- Generate Release Notes
- Publish Release

**Pull request merged**
