### PR TITLE
add arbitrary host mount list

### PR DESCRIPTION
**Pull request by gilesknap**
@marcelldls please can you validate this for me - I don't think I got the json schema change right.

We need this to mount in the Andor SDK for the the Andor3. At least that's what I"m hoping to get permission to do from the cloud team.

@MaxHerbs FYI

### CODE REVIEW

**Comment by gilesknap** [comment]
@marcelldls Now I have just realised that I'd also like to mount arbitrary PVCs too.

So should we add a mountPVCs list into values.yaml, or should we just allow free form entries in the manifests 'volumes' and 'volumeMount' sections (i.e. like we did for tolerations)?

**Comment by marcelldls** [comment]
@gilesknap I think whats different compared to tolerations is that for tolerations we dont have any defaults. I dont really like the idea of making a custom key... Im not sure if theres an easy way but I would hope we could use the standard 'volumes' and 'volumeMount' and join it with whats in the template

**Comment by gilesknap** [comment]
I was just adding another custom key. Would you like to have a go at doing your approach? I think it makes more sense than more custom keys.

**Comment by gilesknap** [comment]
I have a use for this today - want to try making the kernel driver for the andor camera work.

**Comment by marcelldls** [comment]
I would like to have a go, possibly next week? Would be useful for other entries too. Also you have reminded me that the json schema for the argo charts is outdated now...

**Comment by marcelldls** [comment]
> I would like to have a go, possibly next week? Would be useful for other entries too. Also you have reminded me that the json schema for the argo charts is outdated now...

For example, resources

**Comment by gilesknap** [comment]
OK that sounds good. I'm going to make a custom key for now so I can get Max's project working today. 

But we can delete this PR once you have made your changes.

**Comment by marcelldls** [comment]
@gilesknap was this meant to be merged?

**Comment by gilesknap** [comment]
@marcelldls no! 

reverting this here: #42

**Pull request merged**
